### ISSUE TITLE
How to set up?

### ISSUE THREAD

**Issue by spideynn** [foosel/GitIssueBot#3]
I was thinking about using this, but how exactly do I set it up? Some instructions in the README on how to install would be nice (ex. what version of python to use, what packages are needed).

**Comment by marwahaha** [comment]
This is how I'm using it
* python 2.7
* conda install pyyaml
* conda install dateutil
* cloned the repository
* made a new file in the root directory called "moment.yaml", and put my configs there
* made a token https://github.com/blog/1509-personal-api-tokens
* navigate to src/ directory
* python -m gitissuebot.prcheck -c ../moment.yaml

This is the config spec I used
```
blacklisted_targets:
- master
dryrun: true
problems:
  blacklisted_target: '  * Your PR''s target branch `{target_branch}` is among the
    blacklisted target branches: {blacklisted_targets}'
  empty_body: '  * Your PR does have an empty description. Please explain what your
    PR does, how you''ve tested it, etc.'
reminder: 'Hi @{author},


  Thank you for your contribution! Sadly it looks like there is something wrong with
  this PR from branch `{source_branch}` on repository `{source_repo}` to branch `{target_branch}`
  on repository `{target_repo}`:


  {problems}


  Please take a look at the [section on PRs in the Contribution Guidelines](https://github.com/moment/moment/blob/develop/CONTRIBUTING.md)
  and make sure that your PR follows them. Thank you!


  Best regards,

  ~ Your friendly GitIssueBot


  PS: I''m just an automated script, not a human being.

  '
repo: marwahaha/moment
since: 2010-11-18 21:58:24.354836+00:00
token: <insert token here>
```

**Comment by alexeyzimarev** [comment]
The `run` command supposedly should start the bot, but I am getting this:

```
Traceback (most recent call last):
  File "./run", line 11, in <module>
    gitissuebot.main()
  File "/Users/alexey/github/GitIssueBot/src/gitissuebot/__init__.py", line 39, in main
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```
